FROM node:16-alpine

RUN apk add --no-cache bash


EXPOSE 3000
EXPOSE 9229

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm i -g pnpm && pnpm install

COPY . .
RUN pnpm run build

CMD [ "pnpm", "dev" ]