version: '3'

tasks:
  generate:
    cmds:
      - go generate ./...

  migrate-create:
    deps: [generate]
    cmds:
      - atlas migrate diff {{.CLI_ARGS}}
        --dir "file://ent/migrate/migrations"
        --to "ent://ent/schema"
        --dev-url "docker://postgres/15/test?search_path=public"

  dev:
    deps: [generate]
    cmds:
      - go run ./cmd/main.go

  tests:
    deps: [generate]
    cmds:
      - go test -v -parallel=10 -cover ./...
