name = "twitch-notifier"
main = "src/index.ts"
compatibility_date = "2026-03-06"
compatibility_flags = [
	"nodejs_compat"
]
workers_dev = true

[observability]
enabled = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "twitch-notifier-db"
database_id = ""  # Will be filled after creating D1 database
migrations_dir = "./migrations"

[[kv_namespaces]]
binding = "twitch-notifier-kv"
id = "1"

[vars]
BASE_URL = "https://twitch-notifier.satont.workers.dev"
BOT_INFO = """{\"id\":926587718,\"is_bot\":true,\"first_name\":\"Twitch
  Notify\",\"username\":\"TwiNotifyBot\",\"can_join_groups\":true,\"can_read_all_group_messages\":false,\"supports_inline_queries\":false,\"can_connect_to_business\":false,\"has_main_web_app\":false,\"has_topics_enabled\":false,\"allows_users_to_create_topics\":false}"""
TELEGRAM_BOT_ADMINS = "210144787"
TELEGRAM_TOKEN = ""
TWITCH_CLIENT_ID = ""
TWITCH_CLIENT_SECRET = ""
TWITCH_EVENTSUB_SECRET = ""
