// Code generated by ent, DO NOT EDIT.

package chatsettings

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/satont/twitch-notifier/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldLTE(FieldID, id))
}

// GameChangeNotification applies equality check predicate on the "game_change_notification" field. It's identical to GameChangeNotificationEQ.
func GameChangeNotification(v bool) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldEQ(FieldGameChangeNotification, v))
}

// OfflineNotification applies equality check predicate on the "offline_notification" field. It's identical to OfflineNotificationEQ.
func OfflineNotification(v bool) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldEQ(FieldOfflineNotification, v))
}

// GameChangeNotificationEQ applies the EQ predicate on the "game_change_notification" field.
func GameChangeNotificationEQ(v bool) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldEQ(FieldGameChangeNotification, v))
}

// GameChangeNotificationNEQ applies the NEQ predicate on the "game_change_notification" field.
func GameChangeNotificationNEQ(v bool) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldNEQ(FieldGameChangeNotification, v))
}

// OfflineNotificationEQ applies the EQ predicate on the "offline_notification" field.
func OfflineNotificationEQ(v bool) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldEQ(FieldOfflineNotification, v))
}

// OfflineNotificationNEQ applies the NEQ predicate on the "offline_notification" field.
func OfflineNotificationNEQ(v bool) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldNEQ(FieldOfflineNotification, v))
}

// ChatLanguageEQ applies the EQ predicate on the "chat_language" field.
func ChatLanguageEQ(v ChatLanguage) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldEQ(FieldChatLanguage, v))
}

// ChatLanguageNEQ applies the NEQ predicate on the "chat_language" field.
func ChatLanguageNEQ(v ChatLanguage) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldNEQ(FieldChatLanguage, v))
}

// ChatLanguageIn applies the In predicate on the "chat_language" field.
func ChatLanguageIn(vs ...ChatLanguage) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldIn(FieldChatLanguage, vs...))
}

// ChatLanguageNotIn applies the NotIn predicate on the "chat_language" field.
func ChatLanguageNotIn(vs ...ChatLanguage) predicate.ChatSettings {
	return predicate.ChatSettings(sql.FieldNotIn(FieldChatLanguage, vs...))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.ChatSettings {
	return predicate.ChatSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Chat) predicate.ChatSettings {
	return predicate.ChatSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChatSettings) predicate.ChatSettings {
	return predicate.ChatSettings(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChatSettings) predicate.ChatSettings {
	return predicate.ChatSettings(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChatSettings) predicate.ChatSettings {
	return predicate.ChatSettings(func(s *sql.Selector) {
		p(s.Not())
	})
}
