// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/satont/twitch-notifier/ent/chatsettings"
	"github.com/satont/twitch-notifier/ent/predicate"
)

// ChatSettingsDelete is the builder for deleting a ChatSettings entity.
type ChatSettingsDelete struct {
	config
	hooks    []Hook
	mutation *ChatSettingsMutation
}

// Where appends a list predicates to the ChatSettingsDelete builder.
func (csd *ChatSettingsDelete) Where(ps ...predicate.ChatSettings) *ChatSettingsDelete {
	csd.mutation.Where(ps...)
	return csd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (csd *ChatSettingsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ChatSettingsMutation](ctx, csd.sqlExec, csd.mutation, csd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (csd *ChatSettingsDelete) ExecX(ctx context.Context) int {
	n, err := csd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (csd *ChatSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chatsettings.Table, sqlgraph.NewFieldSpec(chatsettings.FieldID, field.TypeUUID))
	if ps := csd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, csd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	csd.mutation.done = true
	return affected, err
}

// ChatSettingsDeleteOne is the builder for deleting a single ChatSettings entity.
type ChatSettingsDeleteOne struct {
	csd *ChatSettingsDelete
}

// Where appends a list predicates to the ChatSettingsDelete builder.
func (csdo *ChatSettingsDeleteOne) Where(ps ...predicate.ChatSettings) *ChatSettingsDeleteOne {
	csdo.csd.mutation.Where(ps...)
	return csdo
}

// Exec executes the deletion query.
func (csdo *ChatSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := csdo.csd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chatsettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (csdo *ChatSettingsDeleteOne) ExecX(ctx context.Context) {
	if err := csdo.Exec(ctx); err != nil {
		panic(err)
	}
}
