// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/satont/twitch-notifier/ent/chat"
	"github.com/satont/twitch-notifier/ent/chatsettings"
	"github.com/satont/twitch-notifier/ent/follow"
	"github.com/satont/twitch-notifier/ent/predicate"
)

// ChatUpdate is the builder for updating Chat entities.
type ChatUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMutation
}

// Where appends a list predicates to the ChatUpdate builder.
func (cu *ChatUpdate) Where(ps ...predicate.Chat) *ChatUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetChatID sets the "chat_id" field.
func (cu *ChatUpdate) SetChatID(s string) *ChatUpdate {
	cu.mutation.SetChatID(s)
	return cu
}

// SetService sets the "service" field.
func (cu *ChatUpdate) SetService(c chat.Service) *ChatUpdate {
	cu.mutation.SetService(c)
	return cu
}

// SetSettingsID sets the "settings" edge to the ChatSettings entity by ID.
func (cu *ChatUpdate) SetSettingsID(id uuid.UUID) *ChatUpdate {
	cu.mutation.SetSettingsID(id)
	return cu
}

// SetNillableSettingsID sets the "settings" edge to the ChatSettings entity by ID if the given value is not nil.
func (cu *ChatUpdate) SetNillableSettingsID(id *uuid.UUID) *ChatUpdate {
	if id != nil {
		cu = cu.SetSettingsID(*id)
	}
	return cu
}

// SetSettings sets the "settings" edge to the ChatSettings entity.
func (cu *ChatUpdate) SetSettings(c *ChatSettings) *ChatUpdate {
	return cu.SetSettingsID(c.ID)
}

// AddFollowIDs adds the "follows" edge to the Follow entity by IDs.
func (cu *ChatUpdate) AddFollowIDs(ids ...uuid.UUID) *ChatUpdate {
	cu.mutation.AddFollowIDs(ids...)
	return cu
}

// AddFollows adds the "follows" edges to the Follow entity.
func (cu *ChatUpdate) AddFollows(f ...*Follow) *ChatUpdate {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return cu.AddFollowIDs(ids...)
}

// Mutation returns the ChatMutation object of the builder.
func (cu *ChatUpdate) Mutation() *ChatMutation {
	return cu.mutation
}

// ClearSettings clears the "settings" edge to the ChatSettings entity.
func (cu *ChatUpdate) ClearSettings() *ChatUpdate {
	cu.mutation.ClearSettings()
	return cu
}

// ClearFollows clears all "follows" edges to the Follow entity.
func (cu *ChatUpdate) ClearFollows() *ChatUpdate {
	cu.mutation.ClearFollows()
	return cu
}

// RemoveFollowIDs removes the "follows" edge to Follow entities by IDs.
func (cu *ChatUpdate) RemoveFollowIDs(ids ...uuid.UUID) *ChatUpdate {
	cu.mutation.RemoveFollowIDs(ids...)
	return cu
}

// RemoveFollows removes "follows" edges to Follow entities.
func (cu *ChatUpdate) RemoveFollows(f ...*Follow) *ChatUpdate {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return cu.RemoveFollowIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ChatMutation](ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChatUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChatUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChatUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChatUpdate) check() error {
	if v, ok := cu.mutation.Service(); ok {
		if err := chat.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "Chat.service": %w`, err)}
		}
	}
	return nil
}

func (cu *ChatUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.ChatID(); ok {
		_spec.SetField(chat.FieldChatID, field.TypeString, value)
	}
	if value, ok := cu.mutation.Service(); ok {
		_spec.SetField(chat.FieldService, field.TypeEnum, value)
	}
	if cu.mutation.SettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chat.SettingsTable,
			Columns: []string{chat.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsettings.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.SettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chat.SettingsTable,
			Columns: []string{chat.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsettings.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.FollowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.FollowsTable,
			Columns: []string{chat.FollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(follow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedFollowsIDs(); len(nodes) > 0 && !cu.mutation.FollowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.FollowsTable,
			Columns: []string{chat.FollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(follow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.FollowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.FollowsTable,
			Columns: []string{chat.FollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(follow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChatUpdateOne is the builder for updating a single Chat entity.
type ChatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMutation
}

// SetChatID sets the "chat_id" field.
func (cuo *ChatUpdateOne) SetChatID(s string) *ChatUpdateOne {
	cuo.mutation.SetChatID(s)
	return cuo
}

// SetService sets the "service" field.
func (cuo *ChatUpdateOne) SetService(c chat.Service) *ChatUpdateOne {
	cuo.mutation.SetService(c)
	return cuo
}

// SetSettingsID sets the "settings" edge to the ChatSettings entity by ID.
func (cuo *ChatUpdateOne) SetSettingsID(id uuid.UUID) *ChatUpdateOne {
	cuo.mutation.SetSettingsID(id)
	return cuo
}

// SetNillableSettingsID sets the "settings" edge to the ChatSettings entity by ID if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableSettingsID(id *uuid.UUID) *ChatUpdateOne {
	if id != nil {
		cuo = cuo.SetSettingsID(*id)
	}
	return cuo
}

// SetSettings sets the "settings" edge to the ChatSettings entity.
func (cuo *ChatUpdateOne) SetSettings(c *ChatSettings) *ChatUpdateOne {
	return cuo.SetSettingsID(c.ID)
}

// AddFollowIDs adds the "follows" edge to the Follow entity by IDs.
func (cuo *ChatUpdateOne) AddFollowIDs(ids ...uuid.UUID) *ChatUpdateOne {
	cuo.mutation.AddFollowIDs(ids...)
	return cuo
}

// AddFollows adds the "follows" edges to the Follow entity.
func (cuo *ChatUpdateOne) AddFollows(f ...*Follow) *ChatUpdateOne {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return cuo.AddFollowIDs(ids...)
}

// Mutation returns the ChatMutation object of the builder.
func (cuo *ChatUpdateOne) Mutation() *ChatMutation {
	return cuo.mutation
}

// ClearSettings clears the "settings" edge to the ChatSettings entity.
func (cuo *ChatUpdateOne) ClearSettings() *ChatUpdateOne {
	cuo.mutation.ClearSettings()
	return cuo
}

// ClearFollows clears all "follows" edges to the Follow entity.
func (cuo *ChatUpdateOne) ClearFollows() *ChatUpdateOne {
	cuo.mutation.ClearFollows()
	return cuo
}

// RemoveFollowIDs removes the "follows" edge to Follow entities by IDs.
func (cuo *ChatUpdateOne) RemoveFollowIDs(ids ...uuid.UUID) *ChatUpdateOne {
	cuo.mutation.RemoveFollowIDs(ids...)
	return cuo
}

// RemoveFollows removes "follows" edges to Follow entities.
func (cuo *ChatUpdateOne) RemoveFollows(f ...*Follow) *ChatUpdateOne {
	ids := make([]uuid.UUID, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return cuo.RemoveFollowIDs(ids...)
}

// Where appends a list predicates to the ChatUpdate builder.
func (cuo *ChatUpdateOne) Where(ps ...predicate.Chat) *ChatUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChatUpdateOne) Select(field string, fields ...string) *ChatUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chat entity.
func (cuo *ChatUpdateOne) Save(ctx context.Context) (*Chat, error) {
	return withHooks[*Chat, ChatMutation](ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChatUpdateOne) SaveX(ctx context.Context) *Chat {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChatUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChatUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChatUpdateOne) check() error {
	if v, ok := cuo.mutation.Service(); ok {
		if err := chat.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "Chat.service": %w`, err)}
		}
	}
	return nil
}

func (cuo *ChatUpdateOne) sqlSave(ctx context.Context) (_node *Chat, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chat.FieldID)
		for _, f := range fields {
			if !chat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.ChatID(); ok {
		_spec.SetField(chat.FieldChatID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Service(); ok {
		_spec.SetField(chat.FieldService, field.TypeEnum, value)
	}
	if cuo.mutation.SettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chat.SettingsTable,
			Columns: []string{chat.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsettings.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.SettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chat.SettingsTable,
			Columns: []string{chat.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatsettings.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.FollowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.FollowsTable,
			Columns: []string{chat.FollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(follow.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedFollowsIDs(); len(nodes) > 0 && !cuo.mutation.FollowsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.FollowsTable,
			Columns: []string{chat.FollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(follow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.FollowsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.FollowsTable,
			Columns: []string{chat.FollowsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(follow.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chat{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
