// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/satont/twitch-notifier/ent/channel"
	"github.com/satont/twitch-notifier/ent/chat"
	"github.com/satont/twitch-notifier/ent/chatsettings"
	"github.com/satont/twitch-notifier/ent/follow"
	"github.com/satont/twitch-notifier/ent/schema"
	"github.com/satont/twitch-notifier/ent/stream"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescIsLive is the schema descriptor for is_live field.
	channelDescIsLive := channelFields[3].Descriptor()
	// channel.DefaultIsLive holds the default value on creation for the is_live field.
	channel.DefaultIsLive = channelDescIsLive.Default.(bool)
	// channelDescUpdatedAt is the schema descriptor for updated_at field.
	channelDescUpdatedAt := channelFields[6].Descriptor()
	// channel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	channel.UpdateDefaultUpdatedAt = channelDescUpdatedAt.UpdateDefault.(func() time.Time)
	// channelDescID is the schema descriptor for id field.
	channelDescID := channelFields[0].Descriptor()
	// channel.DefaultID holds the default value on creation for the id field.
	channel.DefaultID = channelDescID.Default.(func() uuid.UUID)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescID is the schema descriptor for id field.
	chatDescID := chatFields[0].Descriptor()
	// chat.DefaultID holds the default value on creation for the id field.
	chat.DefaultID = chatDescID.Default.(func() uuid.UUID)
	chatsettingsFields := schema.ChatSettings{}.Fields()
	_ = chatsettingsFields
	// chatsettingsDescGameChangeNotification is the schema descriptor for game_change_notification field.
	chatsettingsDescGameChangeNotification := chatsettingsFields[1].Descriptor()
	// chatsettings.DefaultGameChangeNotification holds the default value on creation for the game_change_notification field.
	chatsettings.DefaultGameChangeNotification = chatsettingsDescGameChangeNotification.Default.(bool)
	// chatsettingsDescOfflineNotification is the schema descriptor for offline_notification field.
	chatsettingsDescOfflineNotification := chatsettingsFields[2].Descriptor()
	// chatsettings.DefaultOfflineNotification holds the default value on creation for the offline_notification field.
	chatsettings.DefaultOfflineNotification = chatsettingsDescOfflineNotification.Default.(bool)
	// chatsettingsDescID is the schema descriptor for id field.
	chatsettingsDescID := chatsettingsFields[0].Descriptor()
	// chatsettings.DefaultID holds the default value on creation for the id field.
	chatsettings.DefaultID = chatsettingsDescID.Default.(func() uuid.UUID)
	followFields := schema.Follow{}.Fields()
	_ = followFields
	// followDescID is the schema descriptor for id field.
	followDescID := followFields[0].Descriptor()
	// follow.DefaultID holds the default value on creation for the id field.
	follow.DefaultID = followDescID.Default.(func() uuid.UUID)
	streamFields := schema.Stream{}.Fields()
	_ = streamFields
	// streamDescTitles is the schema descriptor for titles field.
	streamDescTitles := streamFields[2].Descriptor()
	// stream.DefaultTitles holds the default value on creation for the titles field.
	stream.DefaultTitles = streamDescTitles.Default.(pq.StringArray)
	// streamDescCategories is the schema descriptor for categories field.
	streamDescCategories := streamFields[3].Descriptor()
	// stream.DefaultCategories holds the default value on creation for the categories field.
	stream.DefaultCategories = streamDescCategories.Default.(pq.StringArray)
	// streamDescStartedAt is the schema descriptor for started_at field.
	streamDescStartedAt := streamFields[4].Descriptor()
	// stream.DefaultStartedAt holds the default value on creation for the started_at field.
	stream.DefaultStartedAt = streamDescStartedAt.Default.(func() time.Time)
	// streamDescUpdatedAt is the schema descriptor for updated_at field.
	streamDescUpdatedAt := streamFields[5].Descriptor()
	// stream.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	stream.UpdateDefaultUpdatedAt = streamDescUpdatedAt.UpdateDefault.(func() time.Time)
}
