// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/satont/twitch-notifier/ent/channel"
	"github.com/satont/twitch-notifier/ent/chat"
	"github.com/satont/twitch-notifier/ent/chatsettings"
	"github.com/satont/twitch-notifier/ent/follow"
	"github.com/satont/twitch-notifier/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescID is the schema descriptor for id field.
	channelDescID := channelFields[0].Descriptor()
	// channel.DefaultID holds the default value on creation for the id field.
	channel.DefaultID = channelDescID.Default.(func() uuid.UUID)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescID is the schema descriptor for id field.
	chatDescID := chatFields[0].Descriptor()
	// chat.DefaultID holds the default value on creation for the id field.
	chat.DefaultID = chatDescID.Default.(func() uuid.UUID)
	chatsettingsFields := schema.ChatSettings{}.Fields()
	_ = chatsettingsFields
	// chatsettingsDescGameChangeNotification is the schema descriptor for game_change_notification field.
	chatsettingsDescGameChangeNotification := chatsettingsFields[1].Descriptor()
	// chatsettings.DefaultGameChangeNotification holds the default value on creation for the game_change_notification field.
	chatsettings.DefaultGameChangeNotification = chatsettingsDescGameChangeNotification.Default.(bool)
	// chatsettingsDescOfflineNotification is the schema descriptor for offline_notification field.
	chatsettingsDescOfflineNotification := chatsettingsFields[2].Descriptor()
	// chatsettings.DefaultOfflineNotification holds the default value on creation for the offline_notification field.
	chatsettings.DefaultOfflineNotification = chatsettingsDescOfflineNotification.Default.(bool)
	// chatsettingsDescID is the schema descriptor for id field.
	chatsettingsDescID := chatsettingsFields[0].Descriptor()
	// chatsettings.DefaultID holds the default value on creation for the id field.
	chatsettings.DefaultID = chatsettingsDescID.Default.(func() uuid.UUID)
	followFields := schema.Follow{}.Fields()
	_ = followFields
	// followDescID is the schema descriptor for id field.
	followDescID := followFields[0].Descriptor()
	// follow.DefaultID holds the default value on creation for the id field.
	follow.DefaultID = followDescID.Default.(func() uuid.UUID)
}
