// Code generated by ent, DO NOT EDIT.

package stream

import (
	"time"
)

const (
	// Label holds the string label denoting the stream type in the database.
	Label = "stream"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldTitles holds the string denoting the titles field in the database.
	FieldTitles = "titles"
	// FieldCategories holds the string denoting the categories field in the database.
	FieldCategories = "categories"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// Table holds the table name of the stream in the database.
	Table = "streams"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "streams"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
)

// Columns holds all SQL columns for stream fields.
var Columns = []string{
	FieldID,
	FieldChannelID,
	FieldTitles,
	FieldCategories,
	FieldStartedAt,
	FieldUpdatedAt,
	FieldEndedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTitles holds the default value on creation for the "titles" field.
	DefaultTitles []string
	// DefaultCategories holds the default value on creation for the "categories" field.
	DefaultCategories []string
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
