// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// ChatSettings is the predicate function for chatsettings builders.
type ChatSettings func(*sql.Selector)

// Follow is the predicate function for follow builders.
type Follow func(*sql.Selector)
